SHOW CLASSES IN DATABASE SNOWFLAKE;
SHOW CLASSES IN SCHEMA SNOWFLAKE.ML;

SHOW FUNCTIONS IN CLASS CLASSIFICATION;
SHOW PROCEDURES IN CLASS CLASSIFICATION;
SHOW CLASSIFICATION;
SHOW SNOWFLAKE.ML.CLASSIFICATION;

SHOW FUNCTIONS IN CLASS FORECAST;
SHOW PROCEDURES IN CLASS FORECAST;
SHOW FORECAST;

SHOW FUNCTIONS IN CLASS ANOMALY_DETECTION;
SHOW PROCEDURES IN CLASS ANOMALY_DETECTION;
SHOW ANOMALY_DETECTION;

DESCRIBE FUNCTION TOP_INSIGHTS(OBJECT, OBJECT, FLOAT, BOOLEAN);
